### ISSUE TITLE
ERROR Could not pass event PlayerDeathEvent to MultiverseHardcore v1.0

### ISSUE THREAD

**Issue by merami-dies** [lluiscamino/MultiverseHardcore#1]
[Server] INFO java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
15.06 00:08:11 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
15.06 00:08:11 [Server] INFO at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
15.06 00:08:11 [Server] INFO at life.lluis.multiversehardcore.files.PlayersList.addDeathBan(PlayersList.java:105) ~[?:?]
15.06 00:08:11 [Server] INFO at life.lluis.multiversehardcore.events.PlayerDeath.onDeath(PlayerDeath.java:21) ~[?:?]
15.06 00:08:11 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
15.06 00:08:11 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:784) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.die(EntityPlayer.java:598) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:754) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:311) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:298) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:41) ~[?:?]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:103) ~[?:?]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:26) ~[?:?]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:171) ~[?:?]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:557) ~[?:?]
15.06 00:08:11 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) ~[?:?]
15.06 00:08:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1132) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Paper-174]
15.06 00:08:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by lluiscamino** [comment]
Can you please share your `players.yml` and `worlds.yml` files?

**Comment by merami-dies** [comment]
Okay couple more comments. A person can die twice in the world before being kicked out, but once they are kicked out they can go back through a multiverse portal immediately. Perma-death works but temp ban on death does not. Players respawn at their bed on death in hardcore. The nether and end did not generate with my hardcore world so I made them manually, however I've only done death testing in hardcore overworld.


hardcore:
  spectator_mode: 'false'
  ban_ops: 'true'
  ban_forever: 'false'
  respawn_world: 'world'
  ban_length: '9000'
  start_date: '1592118283488'
  include_nether: 'true'
  include_end: 'true'
hardcore_nether:
  spectator_mode: 'false'
  ban_ops: 'true'
  ban_forever: 'false'
  respawn_world: 'world'
  ban_length: '3000'
  start_date: '1592173320271'
  include_nether: 'true'
  include_end: 'true'
hardcore_the_end:
  spectator_mode: 'false'
  ban_ops: 'true'
  ban_forever: 'true'
  respawn_world: 'world'
  ban_length: '3000'
  start_date: '1592173621584'
  include_nether: 'true'
  include_end: 'true'

**Comment by lluiscamino** [comment]
I've released a [new version](https://github.com/lluiscamino/MultiverseHardcore/releases/tag/1.0.1) of the plugin. Please use the new version instead.

Once you've updated the version, try increasing the `enter_world_ticks` value on the `config.yml`.

**Comment by merami-dies** [comment]
I didnt need to update the enter_world_ticks, it just worked. I had to delete my old hardcore folder and readd the world to hardcore though.
