### ISSUE TITLE
Plugin not registering / showing anywhere

### ISSUE THREAD

**Issue by BEMZ01** [lluiscamino/MultiverseHardcore#6]
hello! 
The plugin does not load at all when starting the PaperSpigot server. No relevant info is displayed in the server's console and running /plugins in game does not show the plugin either. 

/paper version:
This server is running paper version git-paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

UPDATE:
**After Downgrading to V1.0 the issue no longer persists.**

**Comment by SoraShiunin** [comment]
Same issue on normal spigot 1.16.5

**Comment by lluiscamino** [comment]
Hello, version 1.0.2 was not compatible with Java 8, therefore the plugin didn't work on some servers.

I've created a new release that is compatible with Java 8, please update to this new version of the plugin: https://github.com/lluiscamino/MultiverseHardcore/releases/tag/1.0.3

Sorry for the inconvenience. Please let me know if this fixes the issue :)

**Comment by SoraShiunin** [comment]
> Hello, version 1.0.2 was not compatible with Java 8, therefore the plugin didn't work on some servers.
> 
> I've created a new release that is compatible with Java 8, please update to this new version of the plugin: https://github.com/lluiscamino/MultiverseHardcore/releases/tag/1.0.3
> 
> Sorry for the inconvenience. Please let me know if this fixes the issue :)

Yes, fixed it! For some reason I din't get the notification for this or forgot to check back.

**Comment by BEMZ01** [comment]
can confirm has fixed the issue.
