### ISSUE TITLE
mvhc permissions

### ISSUE THREAD

**Issue by BEMZ01** [lluiscamino/MultiverseHardcore#8]
Is there any documentation on the permissions for the hardcore. If not could we get a permission similar to banOPs?

**Comment by lluiscamino** [comment]
Hello @BEMZ01,

The plugin doesn't use any other permission system other than the built-in OPs system. Basically, you need to be an OP to use the following commands:

- create
- makehc
- unban
- worlds
- version

Also, OPs don't get death banned in a world if the `ban_ops` flag is set to `true`.

I don't understand what you mean by "If not could we get a permission similar to banOPs". Could you please elaborate on that?
